export { apiFetch } from './client'
export { productsService } from './services/products.service'
export { usersService } from './services/users.service'
export { categoriesService } from './services/categories.service'
export { reviewsService } from './services/reviews.service'
export { ordersService } from './services/orders.service'
export type { paths, components } from './types/api'
